version: '3.8'

services:
  himatika-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - himatika-pdf-worker
    restart: unless-stopped

  himatika-pdf-worker:
    build:
      context: ../himatika-pdf-worker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../himatika-pdf-worker/.env
    restart: unless-stopped
